### ISSUE TITLE
Quickroam doesn't catch org-roam alias

### ISSUE THREAD

**Issue by emacsomancer** [meedstrom/quickroam#2]
Aliases defined in the PROPERTIES header with `:ROAM_ALIASES:` are not picked up by quickroam.

**Comment by meedstrom** [comment]
Aye, that's true.  Now I added a README section about limitations :-)  

It's hard to collect more than 1 property per property drawer with just ripgrep regular expressions because then you need them to be in some alphabetic or otherwise predictable order, and that's before getting into inferring the outline path... which is why I made org-node a different way.  It wound up being faster than my experiments extending the ripgrep method, so, win-win!
